package database

import("database/sql";"fmt")
const loadColumns=`id,date,load_number,loader_id,well_id,ticket_number,miles,driver_id,vec_id,trailer_number,net_weight,tons,ton_rate,total_value,status,ticket_id,created_at,updated_at`
func(d *Database)CreateLoad(v LoadDTO)(*Load,error){if e:=validateLoad(v);e!=nil{return nil,e};r,e:=d.db.Exec(`INSERT INTO load(date,load_number,loader_id,well_id,ticket_number,miles,driver_id,vec_id,trailer_number,net_weight,tons,ton_rate,total_value,status,ticket_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,v.Date,v.LoadNumber,v.LoaderID,v.WellID,v.TicketNumber,v.Miles,v.DriverID,v.VecID,v.TrailerNumber,v.NetWeight,v.Tons,v.TonRate,v.TotalValue,v.Status,v.TicketID);if e!=nil{return nil,databaseError("create load",e)};id,e:=r.LastInsertId();if e!=nil{return nil,databaseError("create load",e)};return d.GetLoad(int(id))}
func(d *Database)GetLoads()([]Load,error){rows,e:=d.db.Query(`SELECT `+loadColumns+` FROM load ORDER BY date DESC,id DESC`);if e!=nil{return nil,databaseError("read loads",e)};defer rows.Close();var out []Load;for rows.Next(){v,e:=scanLoad(rows);if e!=nil{return nil,databaseError("read load",e)};out=append(out,*v)};return out,databaseError("read loads",rows.Err())}
func(d *Database)GetLoad(id int)(*Load,error){v,e:=scanLoad(d.db.QueryRow(`SELECT `+loadColumns+` FROM load WHERE id=?`,id));if e==sql.ErrNoRows{return nil,fmt.Errorf("%w: load",ErrNotFound)};if e!=nil{return nil,databaseError("read load",e)};return v,nil}
func(d *Database)SearchLoads(query string)([]Load,error){items,e:=d.GetLoads();if e!=nil{return nil,e};var out []Load;for _,v:=range items{if containsSimilar(query,v.Date,v.LoadNumber,v.TicketNumber,v.VecID,v.TicketID){out=append(out,v)}};return out,nil}
func(d *Database)UpdateLoad(id int,v LoadDTO)error{if e:=validateLoad(v);e!=nil{return e};r,e:=d.db.Exec(`UPDATE load SET date=?,load_number=?,loader_id=?,well_id=?,ticket_number=?,miles=?,driver_id=?,vec_id=?,trailer_number=?,net_weight=?,tons=?,ton_rate=?,total_value=?,status=?,ticket_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,v.Date,v.LoadNumber,v.LoaderID,v.WellID,v.TicketNumber,v.Miles,v.DriverID,v.VecID,v.TrailerNumber,v.NetWeight,v.Tons,v.TonRate,v.TotalValue,v.Status,v.TicketID,id);if e!=nil{return databaseError("update load",e)};return affected(r,"load")}
func(d *Database)DeleteLoad(id int)error{r,e:=d.db.Exec(`DELETE FROM load WHERE id=?`,id);if e!=nil{return databaseError("delete load",e)};return affected(r,"load")}
func(d *Database)GetLoadsByDriver(driverID int)([]Load,error){if e:=positiveID(driverID,"driver_id");e!=nil{return nil,e};return d.loadsWhere(`driver_id=?`,driverID)}
func(d *Database)GetLoadsByWell(wellID int)([]Load,error){if e:=positiveID(wellID,"well_id");e!=nil{return nil,e};return d.loadsWhere(`well_id=?`,wellID)}
func(d *Database)GetLoadsByStatus(status bool)([]Load,error){return d.loadsWhere(`status=?`,status)}
func(d *Database)loadsWhere(where string,arg any)([]Load,error){rows,e:=d.db.Query(`SELECT `+loadColumns+` FROM load WHERE `+where+` ORDER BY date DESC,id DESC`,arg);if e!=nil{return nil,databaseError("read loads",e)};defer rows.Close();var out []Load;for rows.Next(){v,e:=scanLoad(rows);if e!=nil{return nil,databaseError("read load",e)};out=append(out,*v)};return out,databaseError("read loads",rows.Err())}
