package database

import("database/sql";"fmt")
const vehicleColumns=`id,vec_id,license_id,trailer_number,vin,license_expiration,driver_id,overweight_permit_id,created_at,updated_at`
func(d *Database)CreateVehicle(v VehicleDTO)(*Vehicle,error){if e:=validateVehicle(v);e!=nil{return nil,e};r,e:=d.db.Exec(`INSERT INTO vehicle(vec_id,license_id,trailer_number,vin,license_expiration,driver_id,overweight_permit_id) VALUES(?,?,?,?,?,?,?)`,v.VecID,v.LicenseID,v.TrailerNumber,v.VIN,v.LicenseExpiration,v.DriverID,v.OverweightPermitID);if e!=nil{return nil,databaseError("create vehicle",e)};id,e:=r.LastInsertId();if e!=nil{return nil,databaseError("create vehicle",e)};return d.GetVehicle(int(id))}
func(d *Database)GetVehicles()([]Vehicle,error){rows,e:=d.db.Query(`SELECT `+vehicleColumns+` FROM vehicle ORDER BY id`);if e!=nil{return nil,databaseError("read vehicles",e)};defer rows.Close();var out []Vehicle;for rows.Next(){v,e:=scanVehicle(rows);if e!=nil{return nil,databaseError("read vehicle",e)};out=append(out,*v)};return out,databaseError("read vehicles",rows.Err())}
func(d *Database)GetVehicle(id int)(*Vehicle,error){v,e:=scanVehicle(d.db.QueryRow(`SELECT `+vehicleColumns+` FROM vehicle WHERE id=?`,id));if e==sql.ErrNoRows{return nil,fmt.Errorf("%w: vehicle",ErrNotFound)};if e!=nil{return nil,databaseError("read vehicle",e)};return v,nil}
func(d *Database)SearchVehicles(query string)([]Vehicle,error){items,e:=d.GetVehicles();if e!=nil{return nil,e};var out []Vehicle;for _,v:=range items{if containsSimilar(query,v.VecID,v.LicenseID,v.VIN,v.LicenseExpiration,v.OverweightPermitID){out=append(out,v)}};return out,nil}
func(d *Database)UpdateVehicle(id int,v VehicleDTO)error{if e:=validateVehicle(v);e!=nil{return e};r,e:=d.db.Exec(`UPDATE vehicle SET vec_id=?,license_id=?,trailer_number=?,vin=?,license_expiration=?,driver_id=?,overweight_permit_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,v.VecID,v.LicenseID,v.TrailerNumber,v.VIN,v.LicenseExpiration,v.DriverID,v.OverweightPermitID,id);if e!=nil{return databaseError("update vehicle",e)};return affected(r,"vehicle")}
func(d *Database)DeleteVehicle(id int)error{r,e:=d.db.Exec(`DELETE FROM vehicle WHERE id=?`,id);if e!=nil{return databaseError("delete vehicle",e)};return affected(r,"vehicle")}
