package database

import("database/sql";"fmt")
const vehicleColumns=`id,vec_id,license_id,trailer_number,vin,license_expiration,driver_id,overweight_permit_id,created_at,updated_at`
func(d *Database)CreateVehicle(v VehicleDTO)(*Vehicle,error){for _,x:=range[][2]string{{v.VecID,"vec_id",""},{v.LicenseID,"license_id",""},{v.VIN,"vin",""},{v.LicenseExpiration,"license_expiration",""}}{if e:=required(x[0],x[1]);e!=nil{return nil,e}};r,e:=d.db.Exec(`INSERT INTO vehicle(vec_id,license_id,trailer_number,vin,license_expiration,driver_id,overweight_permit_id) VALUES(?,?,?,?,?,?,?)`,v.VecID,v.LicenseID,v.TrailerNumber,v.VIN,v.LicenseExpiration,v.DriverID,v.OverweightPermitID);if e!=nil{return nil,fmt.Errorf("create vehicle: %w",e)};id,_:=r.LastInsertId();return d.GetVehicle(int(id))}
func(d *Database)GetVehicles()([]Vehicle,error){rows,e:=d.db.Query(`SELECT `+vehicleColumns+` FROM vehicle ORDER BY id`);if e!=nil{return nil,e};defer rows.Close();var out []Vehicle;for rows.Next(){v,e:=scanVehicle(rows);if e!=nil{return nil,e};out=append(out,*v)};return out,rows.Err()}
func(d *Database)GetVehicle(id int)(*Vehicle,error){v,e:=scanVehicle(d.db.QueryRow(`SELECT `+vehicleColumns+` FROM vehicle WHERE id=?`,id));if e==sql.ErrNoRows{return nil,fmt.Errorf("vehicle not found")};return v,e}
func(d *Database)UpdateVehicle(id int,v VehicleDTO)error{r,e:=d.db.Exec(`UPDATE vehicle SET vec_id=?,license_id=?,trailer_number=?,vin=?,license_expiration=?,driver_id=?,overweight_permit_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`,v.VecID,v.LicenseID,v.TrailerNumber,v.VIN,v.LicenseExpiration,v.DriverID,v.OverweightPermitID,id);if e!=nil{return e};return affected(r,"vehicle")}
func(d *Database)DeleteVehicle(id int)error{r,e:=d.db.Exec(`DELETE FROM vehicle WHERE id=?`,id);if e!=nil{return e};return affected(r,"vehicle")}
